### ISSUE TITLE
OC UK address change

### ISSUE THREAD

**Issue by deg-pl** [opencaching/oc_coord#1]
Hi!
Please change www.opencaching.org.uk -> https://opencache.uk
Thanks!

**Comment by andrixnet** [comment]
Fixed in https://github.com/opencaching/oc_coord/pull/2

**Comment by andrixnet** [comment]
Corrected a few mistakes. Repaired in https://github.com/opencaching/oc_coord/pull/4

**Comment by andrixnet** [comment]
Verified and working properly
